/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CFormItem: typeof import('./src/components/CFormItem.vue')['default']
    CInput: typeof import('./src/components/CInput.vue')['default']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDateRange: typeof import('element-plus/es')['ElDateRange']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Preview: typeof import('./src/components/preview/Preview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Temp: typeof import('./src/components/Temp.vue')['default']
    Template: typeof import('./src/components/Template.vue')['default']
  }
}
